# Generated by Django 5.0.3 on 2024-03-24 23:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_MJ", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nome",
        ),
        migrations.AddField(
            model_name="produto",
            name="data_produto",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="produto",
            name="nome_produto",
            field=models.CharField(default="Produto sem nome", max_length=200),
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="produto",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="produto",
            name="visualizacao",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CarrinhoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avaliacao", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_MJ.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_MJ.produto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_MJ.categoria",
            ),
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                ("cidade", models.CharField(max_length=200)),
                ("estado", models.CharField(max_length=200)),
                (
                    "data_cadastro",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("telefone", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carrinho",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_MJ.clientes"
            ),
        ),
        migrations.CreateModel(
            name="Pedido_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordenando_por", models.CharField(max_length=200)),
                ("endereco_envio", models.CharField(max_length=200)),
                ("subtotal", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("telefone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "pedido_status",
                    models.CharField(
                        choices=[
                            ("Pedido Recebido", "Pedido Recebido"),
                            ("Pedido em Processamento", "Pedido em Processamento"),
                            ("Pedido Enviado", "Pedido Enviado"),
                            ("Pedido Entregue", "Pedido Entregue"),
                            ("Pedido Cancelado", "Pedido Cancelado"),
                        ],
                        default="Pedido Recebido",
                        max_length=200,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_MJ.carrinho",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_MJ.clientes",
                    ),
                ),
            ],
        ),
    ]
