# Generated by Django 5.0.3 on 2024-03-31 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_MJ", "0004_alter_produto_nome_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="slug",
        ),
    ]
