# Generated by Django 4.2.11 on 2024-04-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_MJ', '0006_remove_produto_visualizacao_cliente_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
