# Generated by Django 4.2.11 on 2024-04-11 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_MJ", "0008_remove_carrinhoproduto_avaliacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho",
            name="total",
        ),
    ]
