# Generated by Django 4.2.11 on 2024-04-12 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_MJ", "0009_remove_carrinho_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_MJ.carrinho",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_MJ.cliente"
                    ),
                ),
                (
                    "total",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_MJ.total"
                    ),
                ),
            ],
        ),
    ]
