# Generated by Django 5.0.4 on 2024-04-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_MJ", "0011_alter_carrinho_data_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="data_pedido",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="carrinhoproduto",
            name="data_pedido",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="data_cadastro",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="produto",
            name="data_produto",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
